#!/bin/bash

***************************
* This is a script to periodically dump the content of MongoDB
*
* Author	Gavin Abson <gavin.abson@gmail.com>
* Created	2019-01-08
* Modified	2019-01-08
***************************

DBNAME=barmixvah

mongodump -d $DBNAME --gzip -o `dirname $0`/mongobackup
